language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "krasios-github"
    token:
      secure: "be2ebe7389c91041c6e7ac224330835769c3c50a"
jdk:
  - oraclejdk8
script:
  - ant build
  - sonar-scanner